redirectsOrigin = "config"
plugins = []
functionsDirectory = "/Users/jayden/Desktop/SIH FINAL/mindgarden-mern/backend/functions"
functionsDirectoryOrigin = "config"
headers = []

[dev]
framework = "#custom"
targetPort = 3000.0
port = 8888.0
command = "cd frontend && npm run dev"
publish = "frontend/dist"

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "/Users/jayden/Desktop/SIH FINAL/mindgarden-mern/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/jayden/Desktop/SIH FINAL/mindgarden-mern"
command = "cd frontend && npm install && npm run build"
functions = "/Users/jayden/Desktop/SIH FINAL/mindgarden-mern/backend/functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
CI = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]