redirectsOrigin = "config"
plugins = []
headers = []

[dev]
command = "npm run dev"
port = 5173.0
publish = "dist"

[functions]

[functions."*"]

[build]
publish = "/Users/jayden/Desktop/SIH FINAL/mindgarden-mern/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/jayden/Desktop/SIH FINAL/mindgarden-mern/frontend"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "https://mindgarden-backend.onrender.com/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]